### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Ashduc** [OSU-BMBL/scGNN2.0#15]
Hi,
I am new to the scGNN package and I am trying to run it to see the output for the tutorial provided in Seurat.
https://satijalab.org/seurat/articles/pbmc3k_tutorial.html
I read the data and create a Seurat object using Read10X and saved the count matrix using the below command.
pbmc.data <- Read10X(data.dir = "~/seurat/filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
write.table(as.matrix(GetAssayData(object = pbmc, slot = "counts")), '~/counts.csv', sep = ',', row.names = T, col.names = T, quote = F)

Then I use scGNN to read the counts.csv as below
python scGNN_v2.py --load_seurat_object counts.csv --output_dir .\seu_dir\ --total_epoch 31 --feature_AE_epoch 500 300 --output_intermediate  

It successfully reads the data, preprocesses, and goes through the pre-EM runs and Graph AE. When it enters the main loop, I get the below error message. 
**TypeError: 'NoneType' object is not iterable**

Full Error message 
> Entering main loop ...
2023-08-11 10:06:22,512 - --------> Computing all metrics ...
Traceback (most recent call last):
  File "~\scGNN2.0-main\scGNN2.0-main\scGNN_v2.py", line 248, in <module>
    metrics = result.Performance_Metrics(X_sc, X_process, X_feature_recon, edgeList, ct_labels_truth, dropout_info, graph_embed, X_embed, args, param)
  File "~\scGNN2.0-main\scGNN2.0-main\result.py", line 77, in __init__
    self.update(self.cluster_labels_old, X_process, X_feature_recon, edgeList, graph_embed, X_embed, param)
  File "~/scGNN2.0-main\scGNN2.0-main\result.py", line 85, in update
    cluster_index_list = cluster_summary(cluster_label_list)[1]
  File "~\scGNN2.0-main\scGNN2.0-main\clustering.py", line 121, in cluster_output_handler
    for i in range(len(set(listResult))):
TypeError: 'NoneType' object is not iterable

Could you assist with sorting this issue?
Thanks

**Comment by chthub** [comment]
Hi @Ashduc,

The error is reported when calculating performance metrics due to no ground truth cell type label input. You could use `given_cell_type_labels` and `load_cell_type_labels` to set the ground truth label as input.

**Comment by Ashduc** [comment]
Hi @chthub,

I do not have ground truth labels for this analysis. 
How to perform scGNN without ground truth labels?
